### ISSUE TITLE
 Document is not defined when using Lottie in Next.js

### ISSUE THREAD

**Issue by azilRababe** [azilRababe/digihounds#1]
### Description

When using Lottie animations within a Next.js application, I encounter the following error during server-side rendering (SSR):

```
ReferenceError: document is not defined
    at __webpack_require__ (/path/to/webpack-runtime.js:33:43)
    at eval (./components/ui/LottieAnimation.jsx:9:77)
    at (ssr)/./components/ui/LottieAnimation.jsx (/path/to/page.js:140:1)
    at Object.__webpack_require__ [as require] (/path/to/webpack-runtime.js:33:43)
digest: "85290578"
```

**Comment by iamshravan** [comment]
The error ReferenceError: document is not defined indicates that your code is trying to access the document object during the server-side rendering (SSR) phase of your Next.js application. Since document is only available in the browser, you need to ensure that any code relying on it only runs in the client environment.

`"use client";

import React, { useEffect, useState } from "react";
import Lottie from "react-lottie-player";

const LottieAnimation = () => {
  const [animationData, setAnimationData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [isClient, setIsClient] = useState(false); // Track if we are in the client

  useEffect(() => {
    setIsClient(true); // Set to true when the component mounts

    const fetchAnimationData = async () => {
      try {
        const response = await fetch(
          "https://lottie.host/a7afb558-8f71-41ac-b3b3-158253ca5ef7/D8wyY8z95f.json"
        );

        if (!response.ok) {
          throw new Error("Failed to fetch animation data");
        }

        const data = await response.json();
        setAnimationData(data);
      } catch (error) {
        console.error("Error fetching animation data:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchAnimationData();
  }, []);

  if (!isClient) {
    return null; // Render nothing on the server
  }

  if (loading) {
    return <div>Loading animation...</div>;
  }

  return (
    <div>
      {animationData ? (
        <Lottie
          loop
          play
          animationData={animationData}
          style={{ width: 500, height: 500 }}
        />
      ) : (
        <div>Error loading animation.</div>
      )}
    </div>
  );
};

export default LottieAnimation;
`

**Comment by iamshravan** [comment]
Ill push the updated version to hella_kitty
